[package]
name = "configrs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt="*"
confy="*"
anyhow="*"
edit="*"
serde= { version="*", features=["derive"] }
